// <auto-generated />
namespace GATE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangeFKUser_FKStaff_FKStudentRelationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangeFKUser_FKStaff_FKStudentRelationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201707290625560_ChangeFKUser_FKStaff_FKStudentRelationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
